### ISSUE TITLE
How to set the caddy?

### ISSUE THREAD

**Issue by jakkpop** [NS-Sp4ce/V2Ray-With-SSpanel#3]
Following your tutorial, the remote server connects to the panel successfully.
But the connection on the clients doesnt work.
It keeps showing like this below:

> 2019/11/23 09:47:26 127.0.0.1:59406 accepted http://speedtest-sfo2.digitalocean.com/10mb.test  
> 2019/11/23 09:47:41 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxx.com/v2ray): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

And the v2ray log on the remote server showing this:

> 2019/11/23 09:50:08 [Info] SSPanelPlugin: new node info xxx.com;0;16;tls;ws;path=/v2ray|host=xxx.com|inside_port=10550
> 2019/11/23 09:50:08 [Info] SSPanelPlugin: now begin to check users
> 2019/11/23 09:50:08 [Info] SSPanelPlugin: check ports finished. No need to update 
> 2019/11/23 09:50:08 [Info] SSPanelPlugin: Successfully upload 0 users traffics
> 2019/11/23 09:50:08 [Info] SSPanelPlugin: Successfully upload 0 ips
> 2019/11/23 09:50:08 [Info] SSPanelPlugin: Uploaded systemLoad successfully

The caddy config is set like this:
> xxx.com
> {
>   log ./caddy.log
>   proxy /v2ray localhost:2333 {
>     websocket
>     header_upstream -Origin
>   }
> }

And the caddy.log is showing:

> 2019/11/21 09:58:47 [INFO] [xxx.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/1332756363
> 2019/11/21 09:58:47 [INFO] [xxx.com] acme: Could not find solver for: tls-alpn-01
> 2019/11/21 09:58:47 [INFO] [xxx.com] acme: use http-01 solver
> 2019/11/21 09:58:47 [INFO] [xxx.com] acme: Trying to solve HTTP-01
> 2019/11/21 09:58:47 [INFO] [xxx.com] Served key authentication
> 2019/11/21 09:58:47 [INFO] [xxx.com] Served key authentication
> 2019/11/21 09:58:51 [INFO] [xxx.com] The server validated our request
> 2019/11/21 09:58:51 [INFO] [xxx.com] acme: Validations succeeded; requesting certificates
> 2019/11/21 09:58:51 [INFO] [xxx.com] Server responded with a certificate.
> done.
> 
> Serving HTTPS on port 443 
> https://xxx.com
> 
> 
> Serving HTTP on port 80 
> http://xxx.com

Could you please give me some hints?
Thank you so much.

**Comment by NS-Sp4ce** [comment]
Okay, the first thing, for the performance reasons, I **WASN'T USE** any web server (include Nginx or Caddy and some else), because V2ray can establish the server port to wait client connect when you set the right settings.
Second, I noticed your v2ray log has `2019/11/23 09:50:08 [Info] SSPanelPlugin: Successfully upload 0 users traffics`, maybe your have something wrong on your sspanel settings.

**Comment by jakkpop** [comment]
> Okay, the first thing, for the performance reasons, I **WASN'T USE** any web server (include Nginx or Caddy and some else), because V2ray can establish the server port to wait client connect when you set the right settings.
> Second, I noticed your v2ray log has `2019/11/23 09:50:08 [Info] SSPanelPlugin: Successfully upload 0 users traffics`, maybe your have something wrong on your sspanel settings.

Did you mean set the tls+ws in the v2ray config?
I tried for once but failed.

>       "streamSettings": {
>         "network": "ws",
>         "wsSettings": {
>           "path": "/v2ray"
>         },
>         "security": "tls", 
>         "tlsSettings": {
>           "certificates": [
>             {
>               "certificateFile": "/etc/v2ray/v2ray.crt", 
>               "keyFile": "/etc/v2ray/v2ray.key"
>             }
>           ]
>         }
>       }

May I have your config sample?
Thanks a lot.

**Comment by NS-Sp4ce** [comment]
> > Okay, the first thing, for the performance reasons, I **WASN'T USE** any web server (include Nginx or Caddy and some else), because V2ray can establish the server port to wait client connect when you set the right settings.
> > Second, I noticed your v2ray log has `2019/11/23 09:50:08 [Info] SSPanelPlugin: Successfully upload 0 users traffics`, maybe your have something wrong on your sspanel settings.
> 
> Did you mean set the tls+ws in the v2ray config?
> I tried for once but failed.
> 
> > ```
> >   "streamSettings": {
> >     "network": "ws",
> >     "wsSettings": {
> >       "path": "/v2ray"
> >     },
> >     "security": "tls", 
> >     "tlsSettings": {
> >       "certificates": [
> >         {
> >           "certificateFile": "/etc/v2ray/v2ray.crt", 
> >           "keyFile": "/etc/v2ray/v2ray.key"
> >         }
> >       ]
> >     }
> >   }
> > ```
> 
> May I have your config sample?
> Thanks a lot.

For some reasons, I never configure tls+ws successfully (include v2ray.fun or other v2ray projects), maybe you can find solution in this link: https://github.com/NS-Sp4ce/V2Ray-With-SSpanel/issues/2
