### ISSUE TITLE
is your script free or what?

### ISSUE THREAD

**Issue by messi06** [NS-Sp4ce/V2Ray-With-SSpanel#4]
after running for a while : sometimes 1 day , sometimes less , all the servers timeout...
did you limit the script ?

**Comment by NS-Sp4ce** [comment]
> after running for a while : sometimes 1 day , sometimes less , all the servers timeout...
> did you limit the script ?

First, I noticed this script may appear you said on Ali cloud server, maybe  you can create a scheduled task to restart script.
Second, [PLEASE READ THIS PINNED ISSUE](https://github.com/NS-Sp4ce/V2Ray-With-SSpanel/issues/2)

**Comment by messi06** [comment]
honestly man , thank you for your hard work , i appreciate your work , so far your script worked best for me , except the issue that i can't connect after a while , restarting the services / restarting the whole server / restarting the sspanel server / changing the ports/ changing the methods: kcp,tcp,srt / 
>>> i tried all that when the server stops connecting yet nothing seems to be working to fix the issue , i just created a tiny sspanel recently , i am just trying to use v2ray instead of ssr, please tell me if your script is supposed to work all the time without limitations and i am doing sthg wrong or is it just your script because it's free it stops after a while ?
sorry i don't speak chinese but i took a look at your pinned issues , i followed your tutorials ,still this issue happens...
thank you for your patience

**Comment by NS-Sp4ce** [comment]
> honestly man , thank you for your hard work , i appreciate your work , so far your script worked best for me , except the issue that i can't connect after a while , restarting the services / restarting the whole server / restarting the sspanel server / changing the ports/ changing the methods: kcp,tcp,srt /
> 
> > > > i tried all that when the server stops connecting yet nothing seems to be working to fix the issue , i just created a tiny sspanel recently , i am just trying to use v2ray instead of ssr, please tell me if your script is supposed to work all the time without limitations and i am doing sthg wrong or is it just your script because it's free it stops after a while ?
> > > > sorry i don't speak chinese but i took a look at your pinned issues , i followed your tutorials ,still this issue happens...
> > > > thank you for your patience

Honestly, I don't have the source code of this binary file, original author is @rico93, there may be some known or unknown issues in the free version, and  I also encountered that can’t connect to the server. I set a scheduled task to restart the script every 6 hours to solve it.

Maybe you can try execute `systemctl status v2ray -l` on your NODE server, if output like this
```
[Warning] SSPanelPlugin: [http://vipspeedtest1.wuhan.net.cn:8080/speedtest/random2000x2000.jpg] Download error: net/http: request canceled (Client.Timeout exceeded while reading body)
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
try to set a scheduled task  to restart the program every 6 hours to solve it.

**Comment by messi06** [comment]
Feb 03 04:50:13 vultr.guest systemd[1]: Started V2Ray Service.
Feb 03 04:50:13 vultr.guest v2ray[2676]: V2Ray 4.19 (Po) Custom
Feb 03 04:50:13 vultr.guest v2ray[2676]: A unified platform for anti-censorship.
Feb 03 04:50:13 vultr.guest v2ray[2676]: 2020/02/03 04:50:13 [Warning] v2ray.com/core: V2Ray 4.19 started
Feb 03 04:50:17 vultr.guest v2ray[2676]: 2020/02/03 04:50:17 [Warning] SSPanelPlugin: Connected gRPC server "127.0.0.1:2333"
Feb 03 04:50:18 vultr.guest v2ray[2676]: 2020/02/03 04:50:18 [Warning] SSPanelPlugin: Before Update, Current Users 0 need to be add 4 need to be romved 0
Feb 03 04:50:18 vultr.guest v2ray[2676]: 2020/02/03 04:50:18 [Warning] SSPanelPlugin: After Update, Current Users 4 need to be add 0 need to be romved 0
Feb 03 04:51:32 vultr.guest v2ray[2676]: 2020/02/03 04:51:32 [Warning] [1211909703] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
Feb 03 04:51:41 vultr.guest v2ray[2676]: 2020/02/03 04:51:41 [Warning] [4263294638] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.




any idea how to fix this please ?

**Comment by messi06** [comment]
hey , after testing around i figured there is an issue with kcp protocol , using ws or tcp works fine so far , i did this to restart the service every 5 hours like you suggested , i hope it stays stable and working:
crontab -e
0 */5 * * * systemctl restart v2ray
this is what i put in the sspanel node ip input :
nodeip;10550;16;ws;;path=/v2ray|host=bing.com
